### ISSUE TITLE
About the BASE_LR: 0.00005

### ISSUE THREAD

**Issue by pingjun18-li** [bowenc0221/panoptic-deeplab#8] opened 2020-06-16 11:21 UTC
Firstly, thanks for great work
and is it too small we set the base_lr: 0.00005 ?
Look forward to your reply.

**Comment by bowenc0221** [comment] 2020-06-16 15:37
Adam is a little bit different from SGD.
I did a coarse grid search and found this learning rate worked best (for batch size = 4).

**Comment by Alchemist-18** [comment] 2020-06-17 10:52
yeah,I have trained the model with your configs,the losses during training is normal, however,the result of inference is worse. The prediction result pictures of instance panoptic and semantic are all null. the evaluation as follows:
loss:
[06/17 18:48:41 segmentation]: [63200/90000] LR: 0.0000168      Time: 1.259s (1.269s)   Data: 0.032s (0.028s)   Loss: 4.414e-01 (6.416e-01)     Semantic loss: 3.744e-01 (4.303e-01)        Center loss: 3.529e-02 (1.193e-01)      Offset loss: 3.170e-02 (9.203e-02)
[06/17 18:49:13 segmentation]: [63220/90000] LR: 0.0000168      Time: 1.226s (1.269s)   Data: 0.021s (0.028s)   Loss: 5.173e-01 (6.416e-01)     Semantic loss: 3.866e-01 (4.303e-01)        Center loss: 5.590e-02 (1.192e-01)      Offset loss: 7.486e-02 (9.203e-02)

-----------------------------------------
              |    PQ     SQ     RQ     N
All           |   0.1    2.7    0.1    19
Things        |   0.0    0.0    0.0     8
Stuff         |   0.1    4.7    0.2    11


PS:I use the pytorch 1.2, and  modified instance_post_processing.py #35 ctr_hmp_max_pooled = F.pad(ctr_hmp_max_pooled,pad=(1,0,1,0),mode="replicate",value=0), because 'RuntimeError: The size of tensor a (2049) must match the size of tensor b (2048) at non-singleton dimension 3' on 'ctr_hmp[ctr_hmp != ctr_hmp_max_pooled] = -1'.
is it my wrong on pytorch version?  have you seen that?
Thanks for you patient  reply!

**Comment by bowenc0221** [comment] 2020-06-17 15:23
You have to use PyTorch >= 1.3, unfortunately PyTorch 1.2 does not support syncbn. This is why you get such problem.

**Comment by Alchemist-18** [comment] 2020-06-18 09:03
> You have to use PyTorch >= 1.3, unfortunately PyTorch 1.2 does not support syncbn. This is why you get such problem.

Yes,using pytorch1.2 batch =8, I get result 'sem_seg', {'mIoU': 78.89130232692581}
              |    PQ     SQ     RQ     N
All           |  58.3   80.1   71.5    19
Things        |  46.4   78.1   59.3     8
Stuff         |  67.0   81.6   80.4    11
I will update my torch vision and try again.
 by the way, will you release the backbone of Xception that the best performance?
thank you so much!

**Comment by bowenc0221** [comment] 2020-06-18 15:41
Unfortunately, I could not find Xception implementation with ImageNet pre-trained weight in PyTorch. I will figure out how to get similar performance as Xception.

**Comment by Alchemist-18** [comment] 2020-06-19 02:40
Aha, I have tried this project which is  aim to re-produced deeplabv3plus by pytorch,  and the performance is as good as the paper's on PASCAL VOC 2012 val set, my test result is worse on cityscapes, however, the builder has said he also get 75% on cityscapes but have no left the experiment details. May you can try the pre-trained weight of his(As for Xception, we keep the same structure with offical tensorflow code and transform the pretrained parameter file from .ckpt to .pth manually!)
Hope can help you to some extent.
Best Regards!

**Comment by bowenc0221** [comment] 2020-06-19 05:58
Thanks for the pointer. I checked the code, unfortunately, the xception in his implementation is the original xception. We use [xception-65](https://github.com/tensorflow/models/blob/c8f9cf196aa7a9c9554e6005782fd3d71f8d80e4/research/deeplab/core/xception.py#L719) and [xception-71](https://github.com/tensorflow/models/blob/c8f9cf196aa7a9c9554e6005782fd3d71f8d80e4/research/deeplab/core/xception.py#L857) (which is a modified version of xception).

I guess this is why you only got 75% on Cityscapes.

**Comment by guochengqian** [comment] 2020-06-20 23:33
Helllo. @bowenc0221 . 
I attempted to reproduce the results reported in the paper with the default parameters you provided. However, the PQ I got was only 58.7 on cityscapes. 
I used 4 GTX2080ti. 
Do you have any suggestion? Or any idea why it was not able to reproduce?

**Comment by bowenc0221** [comment] 2020-06-21 04:01
The results in my paper use Xception-71 as backbone. This repo currently only supports ResNet-50 backbone. You should get 59.8 PQ with [panoptic_deeplab_R50_os32_cityscapes.yaml](https://github.com/bowenc0221/panoptic-deeplab/blob/master/configs/panoptic_deeplab_R50_os32_cityscapes.yaml).

Batchsize=4 has a large variance, I would suggest you try to use batchsize=8 (with other parameters unchanged).

**Comment by guochengqian** [comment] 2020-06-21 10:15
> The results in my paper use Xception-71 as backbone. This repo currently only supports ResNet-50 backbone. You should get 59.8 PQ with [panoptic_deeplab_R50_os32_cityscapes.yaml](https://github.com/bowenc0221/panoptic-deeplab/blob/master/configs/panoptic_deeplab_R50_os32_cityscapes.yaml).
> 
> Batchsize=4 has a large variance, I would suggest you try to use batchsize=8 (with other parameters unchanged).

Thanks for your prompt reply.

**Comment by Alchemist-18** [comment] 2020-07-17 09:22
hello, I have done the trick of multi_scales and flip as input images to improve the PQ, flip can get about +0.5 PQ, however, when i use the multi_scales the PQ declined, I just reshape the input as the paper's scales and compute the mean of outputs ['semantic','center','offsets'] and resize offsets(*(-1)flip)  ;
is that operation need special processes ?

**Comment by bowenc0221** [comment] 2020-07-17 15:49
Yes, offset needs to be taken special care of. Do you want to submit a PR so I can help you debug and also merge this feature into master?

**Comment by Alchemist-18** [comment] 2020-07-20 01:35
Yes, it's my pleasure,but i can only put my codes on below, because the limited by my computer.
you can try.
firstly, i comment out the codes about "change ASPP"
    # Change ASPP image pooling
    #output_stride = 2 ** (5 - sum(config.MODEL.BACKBONE.DILATION))
    #train_crop_h, train_crop_w = config.TEST.CROP_SIZE
    #scale = 1. / output_stride
    #pool_h = int((float(train_crop_h) - 1.0) * scale + 1.0)
    #pool_w = int((float(train_crop_w) - 1.0) * scale + 1.0)
    #model.set_image_pooling((pool_h, pool_w))
secondly, replace the part 
                image = data.pop('image')
                out_dict = model(image)
by 
                ###multi_scales pingjun.li
                image1 = data['raw_image'][0].cpu().numpy()
                out_dict= muliti_scales_inference(model,image1,scales,config.TEST.FLIP_TEST)
where **muliti_scales_inference** is define as :
    def flip_tensor(x, dim):
        """
        Flip Tensor along a dimension
        """
        dim = x.dim() + dim if dim < 0 else dim
        return x[tuple(slice(None, None) if i != dim
                       else torch.arange(x.size(i) - 1, -1, -1).long()
                       for i in range(x.dim()))]
    def upsample_predictions(pred, input_shape,scale):
        # Override upsample method to correctly handle `offset`
        result = OrderedDict()
        for key in pred.keys():
            out = F.interpolate(pred[key], size=input_shape, mode='bilinear', align_corners=True)
            if 'offset' in key:#The order of second dim is (offset_y, offset_x)
                out *= 1.0/scale
            result[key] = out
        return result

    def muliti_scales_inference(model,raw_image,scales,flip):
        ##transforms
        transforms = T.Compose(
            [   T.ToTensor(),
                T.Normalize(config.DATASET.MEAN,config.DATASET.STD)])
        if flip:
            flip_range = 2
        else:
            flip_range = 1
        h,w,_ = raw_image.shape
        org_h_pad = (h + 31) // 32 * 32 + 1
        org_w_pad = (w + 31) // 32 * 32 + 1

        sum_semantic_with_flip=0
        sum_center_with_flip=0
        sum_offset_with_flip=0
        for i in range(len(scales)):
            image=raw_image
            scale = scales[i]
            raw_h = int(h*scale)
            raw_w = int(w*scale)
            image = cv2.resize(image,(raw_w,raw_h),interpolation=cv2.INTER_NEAREST).astype(np.int32)
            # pad image####
            new_h = (raw_h + 31) // 32 * 32 + 1
            new_w = (raw_w + 31) // 32 * 32 + 1
            input_image = np.zeros((new_h, new_w, 3), dtype=np.uint8)
            input_image[:, :] = config.DATASET.MEAN

            input_image[:raw_h, :raw_w, :] = image

            image, _ = transforms(input_image, None)
            image = image.unsqueeze(0).to(device)
            
            for flip in range(flip_range):
                if flip:
                    image=flip_tensor(image,3)
                out_dict = model(image)
                for key in out_dict.keys(): #return to raw_input shape
                    out_dict[key]=out_dict[key][:,:,:raw_h,:raw_w]

                if raw_h !=org_h_pad or raw_w != org_w_pad:
                    out_dict=upsample_predictions(out_dict,(org_h_pad, org_w_pad),scale)

                semantic_pred=F.softmax(out_dict['semantic'],dim=1)

                center_pred=out_dict['center']
                offset_pred=out_dict['offset']
                if flip:
                    semantic_pred=flip_tensor(semantic_pred,3)
                    center_pred=flip_tensor(center_pred,3)
                    offset_pred=flip_tensor(offset_pred,3)
                    offset_pred[:,1,:,:]*=(-1)

                sum_semantic_with_flip+=semantic_pred
                sum_center_with_flip+=center_pred
                sum_offset_with_flip+=offset_pred
                #pdb.set_trace()

        semantic_mean = sum_semantic_with_flip / (flip_range * len(scales))
        center_mean = sum_center_with_flip / (flip_range * len(scales))
        offset_mean = sum_offset_with_flip / (flip_range * len(scales))
        #semantic_mean_pred = torch.argmax(semantic_mean, dim=1)

        out_dict['semantic']=semantic_mean
        out_dict['center']=center_mean
        out_dict['offset']=offset_mean
        return out_dict

**Comment by bowenc0221** [comment] 2020-07-20 02:02
@Alchemist-18 Thanks for sharing the code! Can you start a new issue for discussion? I think it is beneficial to potential users who are also interested in multi-scale testing.

**Comment by Alchemist-18** [comment] 2020-07-20 02:07
yes, right away

**Comment by bowenc0221** [comment] 2020-07-22 02:00
> Aha, I have tried this project(https://github.com/YudeWang/deeplabv3plus-pytorch) which is aim to re-produced deeplabv3plus by pytorch, and the performance is as good as the paper's on PASCAL VOC 2012 val set, my test result is worse on cityscapes, however, the builder has said he also get 75% on cityscapes but have no left the experiment details. May you can try the pre-trained weight of his(As for Xception, we keep the same structure with offical tensorflow code and transform the pretrained parameter file from .ckpt to .pth manually!)
> Hope can help you to some extent.
> Best Regards!

@pingjun18-li 
FYI, I tried Xception-65 backbone (#27) and it is now in model zoo.

I'm going to close this issue. If you have other question, you are welcome to open a new issue.

**Closed by bowenc0221** 2020-07-22 02:00 UTC
